apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - capability-registry-configmap.yaml
  - kyverno-clusterpolicy-pni-contract-enforce.yaml
  - kyverno-clusterpolicy-pni-reserved-labels-enforce.yaml
  - kyverno-clusterpolicy-pni-capability-validation-enforce.yaml
  - kyverno-clusterpolicy-vault-ca-distribution.yaml
  - ccnp-pni-monitoring-dns-visibility.yaml
  - ccnp-pni-monitoring-vault-config-operator-metrics-egress.yaml
  - ccnp-pni-monitoring-external-secrets-metrics-egress.yaml
  - ccnp-pni-redis-operator-controlplane-egress.yaml
  - ccnp-pni-strimzi-operator-controlplane-egress.yaml
  - ccnp-pni-vault-operator-controlplane-egress.yaml
  - ccnp-pni-external-secrets-controlplane-egress.yaml
  - ccnp-pni-piraeus-operator-controlplane-egress.yaml
  - ccnp-pni-minio-operator-controlplane-egress.yaml
  - ccnp-pni-cnpg-operator-controlplane-egress.yaml
  - ccnp-pni-controlplane-egress-consumer-egress.yaml
  - ccnp-pni-cnpg-operator-dataplane-egress.yaml
  - ccnp-pni-redis-operator-dataplane-egress.yaml
  - ccnp-pni-strimzi-operator-dataplane-egress.yaml
  - ccnp-pni-s3-object-consumer-egress.yaml
  - ccnp-pni-cnpg-postgres-consumer-egress.yaml
  - ccnp-pni-vault-secrets-consumer-egress.yaml
  - ccnp-pni-redis-managed-consumer-egress.yaml
  - ccnp-pni-kafka-managed-consumer-egress.yaml
  - ccnp-pni-gateway-backend-consumer-ingress.yaml
  - ccnp-pni-monitoring-scrape-consumer-egress.yaml
  - ccnp-pni-internet-egress-consumer-egress.yaml
