apiVersion: v1
kind: Secret
metadata:
  name: myminio-env-configuration
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_PROMETHEUS_AUTH_TYPE="public"
