apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: homelab
  namespace: piraeus-datastore
  labels:
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: linstor-cluster
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  nodeSelector:
    matchLabels:
      feature.node.kubernetes.io/storage-nvme.present: "true"
  apiTLS:
    certManager:
      kind: Issuer
      name: linstor-api-ca
  internalTLS:
    certManager:
      kind: Issuer
      name: linstor-internal-ca
