apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: ip-pool
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  # Reserve this pool for the Gateway API Service only.
  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: homelab-gateway
  blocks:
    - cidr: 192.168.2.70/32
