apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-ui-l2
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: l2-announcement
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  serviceSelector:
    matchLabels:
      homelab.local/expose: "true"
  loadBalancerIPs: true
