apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

resources:
  - gateway.yaml
  - gatewayclass-config.yaml
  - certificate.yaml
  - cilium-ip-pool.yaml
  - cilium-ui-ip-pool.yaml
  - cilium-l2-announcement.yaml
  - cilium-l2-announcement-ui.yaml
  - httproute-redirect.yaml
