apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
    targetRevision: v0.10.3
    path: deploy/standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
