apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: forgejo-bootstrap-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - forgejo-bootstrap-secret.sops.yaml
