apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: network-connect-external
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: runtime-security
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  podSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: In
        values:
          - kube-system
          - argocd
          - tetragon
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs: []
